data.raw["dont-build-entity-achievement"]["raining-bullets"] = nil
data.raw["combat-robot-count"]["minions"] = nil
data.raw["dont-build-entity-achievement"]["logistic-network-embargo"] = nil
data.raw["research-achievement"]["raining-bullets"] = nil
data.raw["dont-use-entity-in-energy-production-achievement"]["steam-all-the-way"] = nil
data.raw["dont-craft-manually-achievement"]["lazy-bastard"] = nil
data.raw["construct-with-robots-achievement"]["you-are-doing-it-right"] = nil
data.raw["research-achievement"]["eco-unfriendly"] = nil
data.raw["kill-achievement"]["minions"] = nil
data.raw["construct-with-robots-achievement"]["automated-construction"].amount = 10
data.raw["deconstruct-with-robots-achievement"]["automated-cleanup"].amount = 10
data.raw["deliver-by-robots-achievement"]["you-have-got-a-package"].amount = 1
data.raw["deliver-by-robots-achievement"]["delivery-service"].amount = 100
data.raw["train-path-achievement"]["trans-factorio-express"].amount = 100
data.raw["player-damaged-achievement"]["watch-your-step"].minimum_damage = 0
data.raw["player-damaged-achievement"]["golem"].minimum_damage = 500
data.raw["build-entity-achievement"]["getting-on-track-like-a-pro"].until_second = 200 * 600
data.raw["produce-achievement"]["mass-production-1"].amount = 10
data.raw["produce-achievement"]["mass-production-2"].amount = 100
data.raw["produce-achievement"]["mass-production-3"].amount = 200
data.raw["produce-per-hour-achievement"]["circuit-veteran-1"].amount = 10
data.raw["produce-per-hour-achievement"]["circuit-veteran-2"].amount = 50
data.raw["produce-per-hour-achievement"]["circuit-veteran-3"].amount = 100
data.raw["produce-per-hour-achievement"]["computer-age-1"].amount = 50
data.raw["produce-per-hour-achievement"]["computer-age-2"].amount = 100
data.raw["produce-per-hour-achievement"]["computer-age-3"].amount = 500
data.raw["produce-per-hour-achievement"]["iron-throne-1"].amount = 200
data.raw["produce-per-hour-achievement"]["iron-throne-2"].amount = 2000
data.raw["produce-per-hour-achievement"]["iron-throne-3"].amount = 4000
data.raw["kill-achievement"]["steamrolled"].amount = 10
data.raw["kill-achievement"]["pyromaniac"].amount = 100
data.raw["kill-achievement"]["run-forrest-run"].amount = 10
data.raw["finish-the-game-achievement"]["no-time-for-chitchat"].until_second = 600 * 60 * 15
data.raw["finish-the-game-achievement"]["there-is-no-spoon"].until_second = 600 * 60 * 8