data.raw["recipe"]["nuclear-fuel-reprocessing"].hidden=true 
data.raw["recipe"]["kovarex-enrichment-process"].hidden=true 
data.raw["recipe"]["small-electric-pole"].enabled=false 
data.raw["recipe"]["medium-electric-pole"].enabled=true 
data.raw["recipe"]["iron-stick"].enabled=false 
data.raw["recipe"]["basic-oil-processing"].results={{type="fluid", name="heavy-oil", amount=500}}
data.raw["recipe"]["laser-turret"].ingredients ={{"iron-gear-wheel", 10},{"electronic-circuit", 10},{"battery", 10}}
data.raw["recipe"]["artillery-turret"].ingredients ={{"iron-gear-wheel", 40},{"advanced-circuit", 20},{"concrete", 10}}
data.raw["recipe"]["battery-equipment"].ingredients ={{"battery", 10}}
data.raw["recipe"]["solar-panel-equipment"].ingredients ={{"solar-panel", 1}}
data.raw["recipe"]["personal-roboport-equipment"].ingredients ={{"advanced-circuit", 10},{"iron-gear-wheel", 10},{"battery", 10}}
data.raw["recipe"]["stone-furnace"].ingredients = {{"stone", 1}}
data.raw["recipe"]["boiler"].ingredients = {{"stone-furnace", 1},{"iron-plate",1}}
data.raw["recipe"]["steam-engine"].ingredients = {{"iron-plate", 5},{"iron-gear-wheel", 1}}
data.raw["recipe"]["iron-gear-wheel"].normal.ingredients = {{"iron-plate", 1}}
data.raw["recipe"]["iron-gear-wheel"].result_count = 2
data.raw["recipe"]["electronic-circuit"].normal.ingredients = {{"copper-cable", 1},{"iron-plate",1}}
data.raw["recipe"]["electronic-circuit"].result_count = 2
data.raw["recipe"]["transport-belt"].ingredients = {{"iron-plate", 2}}
data.raw["recipe"]["transport-belt"].result_count = 4
data.raw["recipe"]["electric-mining-drill"].normal.ingredients = {{"burner-mining-drill", 1},{"iron-plate",1}}
data.raw["recipe"]["burner-mining-drill"].ingredients = {{"iron-ore",1}}
data.raw["recipe"]["inserter"].ingredients = {{"burner-inserter",1}}
data.raw["recipe"]["burner-inserter"].ingredients = {{"iron-plate", 1}}
data.raw["recipe"]["pipe"].ingredients = {{"iron-plate", 1}}
data.raw["recipe"]["pipe"].result_count = 6
data.raw["recipe"]["medium-electric-pole"].enabled = true
data.raw["recipe"]["medium-electric-pole"].ingredients = {{"iron-plate", 1},{"copper-plate", 2}}
data.raw["recipe"]["advanced-circuit"].ingredients = {        {"electronic-circuit", 1},       {"plastic-bar", 1}      }
data.raw["recipe"]["artillery-shell"].ingredients = {      {"explosive-cannon-shell", 5},      {"advanced-circuit", 5},    }
data.raw["recipe"]["artillery-targeting-remote"].ingredients = {      {"advanced-circuit", 1},      {"iron-plate", 10}    }
data.raw["recipe"]["artillery-wagon"].ingredients={{"iron-gear-wheel", 10},{"iron-plate", 40},{"cargo-wagon", 1},{"advanced-circuit", 10}}
data.raw["recipe"]["assembling-machine-1"].ingredients = {{"electronic-circuit", 2},{"iron-gear-wheel", 5}    }
data.raw["recipe"]["assembling-machine-2"].normal.ingredients = {        {"iron-gear-wheel", 5},        {"assembling-machine-1", 1}      }
data.raw["recipe"]["assembling-machine-3"].ingredients = {      {"electronic-circuit", 2},{"iron-gear-wheel", 5},  {"assembling-machine-2", 2}    }
data.raw["recipe"]["battery"].normal.ingredients = {{type="fluid", name="heavy-oil", amount=50},        {"iron-plate", 2},        {"copper-plate", 2}}
data.raw["recipe"]["cannon-shell"].ingredients = {        {"steel-plate", 2},        {"explosives", 1},      }
data.raw["recipe"]["car"].ingredients = {      {"engine-unit", 2},      {"copper-plate", 20},	  {"iron-gear-wheel", 10},    }
data.raw["recipe"]["cargo-wagon"].ingredients = {      {"iron-gear-wheel", 10},      {"iron-plate", 20}    }
data.raw["recipe"]["chemical-plant"].ingredients = {{"iron-gear-wheel", 5},{"electronic-circuit", 5},{"pipe", 5}}
data.raw["recipe"]["concrete"].ingredients =  {      {"stone-brick", 20},    }
data.raw["recipe"]["construction-robot"].ingredients = {      {"iron-gear-wheel", 2},      {"electronic-circuit", 2}    }
data.raw["recipe"]["copper-plate"].energy_required = 3.5
data.raw["recipe"]["defender-capsule"].ingredients = {{"firearm-magazine", 100},{"electronic-circuit", 5},{"iron-gear-wheel", 3}}
data.raw["recipe"]["explosive-cannon-shell"].normal.ingredients = {{"defender-capsule", 1},{"iron-plate", 20}}
data.raw["recipe"]["defender-capsule"].enabled = true
data.raw["recipe"]["electric-furnace"].ingredients = {{"stone-furnace", 2}, {"advanced-circuit", 3}}
data.raw["recipe"]["engine-unit"].ingredients = {      {"iron-plate", 3},      {"iron-gear-wheel", 2},      {"pipe", 2}    }
data.raw["recipe"]["explosives"].ingredients = {{type="item", name="grenade", amount=1},{type="item", name="coal", amount=1},{type="fluid", name="steam", amount=10}}
data.raw["recipe"]["express-splitter"].ingredients = {	{"iron-gear-wheel", 5},      {"fast-splitter", 1}    }
data.raw["recipe"]["express-transport-belt"].ingredients = {        {"iron-gear-wheel",5},        {"fast-transport-belt", 1},      }
data.raw["recipe"]["express-underground-belt"].ingredients = {      {"iron-gear-wheel",5},	  {"fast-underground-belt", 2}    }
data.raw["recipe"]["fast-inserter"].ingredients = {      {"inserter", 1}    }
data.raw["recipe"]["fast-splitter"].ingredients = {      {"splitter", 1},    }
data.raw["recipe"]["fast-transport-belt"].ingredients = {      {"transport-belt", 1}    }
data.raw["recipe"]["fast-underground-belt"].ingredients = {      {"underground-belt", 2}    }
data.raw["recipe"]["filter-inserter"].ingredients = {      {"fast-inserter", 1},    }
data.raw["recipe"]["firearm-magazine"].ingredients = {{"iron-plate",1}}
data.raw["recipe"]["fluid-wagon"].ingredients = {      {"cargo-wagon", 1},      {"storage-tank", 1},      {"pipe", 10}    }
data.raw["recipe"]["gate"].ingredients = {{"stone-wall", 1},{"electronic-circuit",1}}
data.raw["recipe"]["grenade"].ingredients = {      {"iron-plate", 1},      {"coal", 1},    }
data.raw["recipe"]["heat-exchanger"].ingredients = {{"iron-plate", 10}, {"copper-plate", 10}, {"pipe", 10}}
data.raw["recipe"]["heat-pipe"].ingredients = {{"iron-plate", 5}, {"copper-plate", 5}}
data.raw["recipe"]["heavy-armor"].ingredients = {{ "copper-plate", 1}, {"iron-plate", 25}}
data.raw["recipe"]["utility-science-pack"].ingredients = {      {"battery", 1},      {"processing-unit", 3}    }
data.raw["recipe"]["iron-chest"].ingredients = {{"iron-plate", 8}}
data.raw["recipe"]["iron-plate"].energy_required = 3.5
data.raw["recipe"]["lab"].ingredients = {      {"electronic-circuit", 5},    }
data.raw["recipe"]["landfill"].ingredients = {      {"stone", 1}    }
data.raw["recipe"]["light-armor"].ingredients = {{"iron-plate", 40}}
data.raw["recipe"]["locomotive"].ingredients = {{"engine-unit", 2},      {"electronic-circuit", 20},      {"iron-gear-wheel", 20}    }
data.raw["recipe"]["logistic-chest-active-provider"].ingredients =  {{"iron-chest", 1}}
data.raw["recipe"]["logistic-chest-buffer"].ingredients =  {{"iron-chest", 1}}
data.raw["recipe"]["logistic-chest-passive-provider"].ingredients = {{"iron-chest", 1}}
data.raw["recipe"]["logistic-chest-requester"].ingredients =  {{"iron-chest", 1}}
data.raw["recipe"]["logistic-chest-storage"].ingredients =  {{"iron-chest", 1}}
data.raw["recipe"]["logistic-robot"].ingredients = {      {"copper-cable", 2},      {"advanced-circuit", 2}    }
data.raw["recipe"]["long-handed-inserter"].ingredients = {      {"inserter", 1}    }
data.raw["recipe"]["military-science-pack"].ingredients = {      {"grenade", 1},      {"pistol", 1}    }
data.raw["recipe"]["modular-armor"].ingredients = {      {"electronic-circuit", 3},      {"iron-plate", 20}    }
data.raw["recipe"]["nuclear-reactor"].ingredients = {{"concrete", 50},{"iron-plate", 50},{"advanced-circuit", 20}}
data.raw["recipe"]["offshore-pump"].ingredients = {      {"pipe", 1},    }
data.raw["recipe"]["oil-refinery"].ingredients = {{"iron-plate", 15},{"stone-brick", 10},{"electronic-circuit", 10},{"pipe", 20}}
data.raw["recipe"]["piercing-rounds-magazine"].ingredients = {      {"firearm-magazine", 1},      {"copper-plate", 1}    }
data.raw["recipe"]["pipe-to-ground"].ingredients = {      {"pipe", 5},	      }
data.raw["recipe"]["pistol"].ingredients = {      {"iron-plate", 5}    }
data.raw["recipe"]["processing-unit"].normal.ingredients = {{"electronic-circuit", 3},{"advanced-circuit", 3},{type="fluid", name="steam", amount=10}}
data.raw["recipe"]["production-science-pack"].ingredients = {{"engine-unit", 3},{"electric-furnace", 3}}
data.raw["recipe"]["pumpjack"].ingredients = {{"iron-plate", 20},{"iron-gear-wheel", 5},{"pipe", 10}}
data.raw["recipe"]["radar"].ingredients = {      {"iron-ore", 10}    }
data.raw["recipe"]["rail"].ingredients = {      {"stone", 2},      {"iron-plate", 4}    }
data.raw["recipe"]["rail"].result_count = 10
data.raw["recipe"]["rail-chain-signal"].ingredients = {      {"electronic-circuit", 1}    }
data.raw["recipe"]["rail-signal"].ingredients = {      {"electronic-circuit", 1}    }
data.raw["recipe"]["repair-pack"].ingredients = {      {"iron-plate", 1}    }
data.raw["recipe"]["roboport"].ingredients = {      {"iron-plate", 10},      {"iron-gear-wheel", 10},      {"advanced-circuit", 10}    }
data.raw["recipe"]["rocket-control-unit"].ingredients = {      {"processing-unit", 2},      {"defender-capsule", 1}    }
data.raw["recipe"]["rocket-fuel"].ingredients = {      {"coal", 10},{"uranium-ore", 10}    }
data.raw["recipe"]["rocket-part"].ingredients = {      {"rocket-control-unit", 5},      {"rocket-fuel", 5},    }
data.raw["recipe"]["rocket-silo"].ingredients = {{"iron-plate", 60},{"concrete", 60},{"pipe", 100},{"processing-unit", 200}}
data.raw["recipe"]["satellite"].ingredients = {{"solar-panel", 50},{"radar", 100}}
data.raw["recipe"]["automation-science-pack"].ingredients = {      {"iron-gear-wheel", 1},{"copper-plate",1}    }
data.raw["recipe"]["logistic-science-pack"].ingredients = {      {"electronic-circuit", 1},      {"transport-belt", 4}	        }
data.raw["recipe"]["chemical-science-pack"].ingredients = {      {"advanced-circuit", 2},      {"rail", 2}    }
data.raw["recipe"]["shotgun"].ingredients = {      {"pistol",3}    }
data.raw["recipe"]["shotgun-shell"].ingredients = {	{"iron-plate",1}     }
data.raw["recipe"]["solar-panel"].ingredients = {      {"iron-plate", 10},      {"electronic-circuit", 10}    }
data.raw["recipe"]["splitter"].ingredients = {      {"underground-belt", 1}    }
data.raw["recipe"]["steam-turbine"].ingredients = {{"iron-gear-wheel", 5}, {"copper-plate", 10}, {"pipe", 10}}
data.raw["recipe"]["stone-brick"].energy_required = 3.5
data.raw["recipe"]["stone-wall"].ingredients = {{"stone-brick", 1}}
data.raw["recipe"]["stone-wall"].result_count = 5
data.raw["recipe"]["storage-tank"].ingredients = {      {"pipe", 2},      {"iron-plate", 10}    }
data.raw["recipe"]["submachine-gun"].ingredients = {        {"pistol",2}		}
data.raw["recipe"]["tank"].normal.ingredients = {        {"car", 1},{"engine-unit", 2},        {"iron-plate", 10}      }
data.raw["recipe"]["energy-shield-equipment"].ingredients = {{"engine-unit", 2},        {"plastic-bar", 10}      }
data.raw["recipe"]["train-stop"].ingredients = {      {"electronic-circuit", 2},      {"iron-plate", 2}    }
data.raw["recipe"]["underground-belt"].ingredients = {      {"transport-belt", 1}    }
data.raw["recipe"]["uranium-fuel-cell"].ingredients = {{"uranium-ore", 30},{"iron-plate", 30},}
data.raw["recipe"]["underground-belt"].ingredients = {      {"transport-belt", 1}    }
data.raw["recipe"]["plastic-bar"].ingredients = {{type="fluid", name="crude-oil", amount=2},{"coal", 2}}
