require("prototypes.achievements")
require("prototypes.ambient-sounds")
require("prototypes.autobarrel")
require("prototypes.decoratives")
require("prototypes.entity")
require("prototypes.recipe")
require("prototypes.technology")
