require("prototypes.entity._others")
require("prototypes.entity.assembling-machine")
require("prototypes.entity.character")
require("prototypes.entity.mining-drill")
require("prototypes.recipe")
require("prototypes.technology")
