-- See prototypes.fluid for un/barreling recipes, generated by the
-- same builtin as the default recipes.

-- basic-oil-processing
data.raw["recipe"]["basic-oil-processing"].results =
{
    {type="fluid", name="LaNMod-oil", amount=45, fluidbox_index = 3}
}

-- advanced-oil-processing
data.raw["recipe"]["advanced-oil-processing"].ingredients =
{
    {type="fluid", name="steam", amount=50},
    {type="fluid", name="crude-oil", amount=100}
}
data.raw["recipe"]["advanced-oil-processing"].results =
{
    {type="fluid", name="LaNMod-oil", amount=120, fluidbox_index = 3}
}

-- coal-liquefaction
data.raw["recipe"]["coal-liquefaction"].ingredients =
{
    {type="item", name="coal", amount=20},
    {type="fluid", name="LaNMod-oil", amount=20},
    {type="fluid", name="steam", amount=50}
}
data.raw["recipe"]["coal-liquefaction"].results =
{
    {type="fluid", name="LaNMod-oil", amount=120, fluidbox_index = 3}
}
data.raw["recipe"]["coal-liquefaction"].icon = "__LaNMod__/graphics/icons/fluid/coal-liquefaction.png"

-- heavy-oil-cracking
data.raw["recipe"]["heavy-oil-cracking"] = nil

-- light-oil-cracking
data.raw["recipe"]["light-oil-cracking"] = nil

-- sulfuric-acid
-- No changes to sulfuric acid.

-- plastic-bar
data.raw["recipe"]["plastic-bar"].ingredients =
{
    {type="fluid", name="LaNMod-oil", amount=40},
    {type="item", name="coal", amount=4}
}
data.raw["recipe"]["plastic-bar"].results =
{
    {type="item", name="plastic-bar", amount=4}
}

-- solid-fuel-from-light-oil
data.raw["recipe"]["solid-fuel-from-light-oil"] = nil
-- solid-fuel-from-petroleum-gas
data.raw["recipe"]["solid-fuel-from-petroleum-gas"] = nil
-- solid-fuel-from-heavy-oil
data.raw["recipe"]["solid-fuel-from-heavy-oil"] = nil

-- solid-fuel-from-LaNMod-oil
data:extend(
{
    {
        type = "recipe",
        name = "solid-fuel-from-LaNMod-oil",
        category = "chemistry",
        energy_required = 2,
        ingredients =
        {
            {type="fluid", name="LaNMod-oil", amount=20}
        },
        results=
        {
            {type="item", name="solid-fuel", amount=1}
        },
        icon = "__LaNMod__/graphics/icons/solid-fuel-from-LaNMod-oil.png",
        icon_size = 32,
        subgroup = "fluid-recipes",
        enabled = false,
        order = "b[fluid-chemistry]-e[solid-fuel-from-LaNMod-oil]",
        crafting_machine_tint =
        {
            primary = {r = 0.889, g = 0.628, b = 0.566, a = 1.000}, -- #e2a090ff
            secondary = {r = 0.803, g = 0.668, b = 0.644, a = 1.000}, -- #ccaaa4ff
            tertiary = {r = 0.854, g = 0.659, b = 0.576, a = 1.000}, -- #d9a892ff
            quaternary = {r = 1.000, g = 0.395, b = 0.127, a = 1.000}, -- #ff6420ff
        }
    }
})

-- sulfur
data.raw["recipe"]["sulfur"].ingredients =
{
    {type="fluid", name="water", amount=30},
    {type="item", name="coal", amount=10}
}

-- lubricant
data.raw["recipe"]["lubricant"].ingredients =
{
    {type="fluid", name="LaNMod-oil", amount=10},
    {type="fluid", name="steam", amount=10},
    {type="item", name="sulfur", amount=4}
}

-- empty-barrel
-- No changes to empty barrel (the one from steel).
