-- See prototypes.fluid for un/barreling recipes, generated by the
-- same builtin as the default recipes.

-- basic-oil-processing
data.raw["recipe"]["basic-oil-processing"].ingredients =
{
    {type="fluid", name="steam", amount=20, fluidbox_index = 1},
    {type="fluid", name="crude-oil", amount=100, fluidbox_index = 2}
}
data.raw["recipe"]["basic-oil-processing"].results =
{
    {type="fluid", name="LaNMod-oil", amount=60, fluidbox_index = 3},
}

-- advanced-oil-processing
data.raw["recipe"]["advanced-oil-processing"].ingredients =
{
    {type="fluid", name="steam", amount=50, fluidbox_index = 1},
    {type="fluid", name="crude-oil", amount=100, fluidbox_index = 2}
}
data.raw["recipe"]["advanced-oil-processing"].results =
{
    {type="fluid", name="LaNMod-oil", amount=160, fluidbox_index = 3}
}
-- Used to get the product to appear in the tooltip if one product:
data.raw["recipe"]["advanced-oil-processing"].main_product = ""

-- coal-liquefaction
data.raw["recipe"]["coal-liquefaction"].ingredients =
{
    {type="item", name="coal", amount=20},
    {type="fluid", name="steam", amount=60, fluidbox_index = 1},
    {type="fluid", name="LaNMod-oil", amount=20, fluidbox_index = 2}
}
data.raw["recipe"]["coal-liquefaction"].results =
{
    {type="fluid", name="LaNMod-oil", amount=100, fluidbox_index = 3}
}
data.raw["recipe"]["coal-liquefaction"].icon = "__LaNMod__/graphics/icons/fluid/coal-liquefaction.png"
-- Used to get the product to appear in the tooltip if one product:
data.raw["recipe"]["coal-liquefaction"].main_product = ""

-- heavy-oil-cracking
data.raw["recipe"]["heavy-oil-cracking"] = nil

-- light-oil-cracking
data.raw["recipe"]["light-oil-cracking"] = nil

-- sulfuric-acid
data.raw["recipe"]["sulfuric-acid"].order = "h[sulfuric-acid]"

-- plastic-bar
data.raw["recipe"]["plastic-bar"].ingredients =
{
    {type="fluid", name="LaNMod-oil", amount=40},
    {type="item", name="coal", amount=4}
}
data.raw["recipe"]["plastic-bar"].results =
{
    {type="item", name="plastic-bar", amount=4}
}

-- solid-fuel-from-light-oil
data.raw["recipe"]["solid-fuel-from-light-oil"] = nil
-- solid-fuel-from-petroleum-gas
data.raw["recipe"]["solid-fuel-from-petroleum-gas"] = nil
-- solid-fuel-from-heavy-oil
data.raw["recipe"]["solid-fuel-from-heavy-oil"] = nil

-- solid-fuel-from-LaNMod-oil
data:extend(
{
    {
        type = "recipe",
        name = "solid-fuel-from-LaNMod-oil",
        category = "chemistry",
        energy_required = 2,
        ingredients =
        {
            {type="fluid", name="LaNMod-oil", amount=20}
        },
        results=
        {
            {type="item", name="solid-fuel", amount=1}
        },
        icon = "__base__/graphics/icons/solid-fuel.png",
        icon_size = 32,
        subgroup = "fluid-recipes",
        enabled = false,
        order = "b-c",
        crafting_machine_tint =
        {
            primary = {r = 0.768, g = 0.631, b = 0.768, a = 1.000}, -- #c3a0c3ff
            secondary = {r = 0.659, g = 0.592, b = 0.678, a = 1.000}, -- #a896acff
            tertiary = {r = 0.774, g = 0.631, b = 0.766, a = 1.000}, -- #c5a0c3ff
            quaternary = {r = 0.564, g = 0.364, b = 0.564, a = 1.000}, -- #8f5c8fff
        }
    }
})

-- oxidizer
data:extend(
{
    {
        type = "recipe",
        name = "oxidizer",
        category = "chemistry",
        energy_required = 2,
        ingredients =
        {
            {type="item", name="sulfur", amount=20},
            {type="fluid", name="LaNMod-oil", amount=10}
        },
        results=
        {
            {type="item", name="oxidizer", amount=1}
        },
        icon = "__LaNMod__/graphics/icons/oxidizer.png",
        icon_size = 32,
        subgroup = "fluid-recipes",
        enabled = false,
        order = "b-d",
        crafting_machine_tint =
        {
            primary = {r = 0.894, g = 0.863, b = 0.808, a = 1.000}, -- #e4dcceff
            secondary = {r = 1.000, g = 0.902, b = 0.812, a = 1.000}, -- #ffe6cfff
            tertiary = {r = 0.834, g = 0.818, b = 0.666, a = 1.000}, -- #d5d1aaff
            quaternary = {r = 0.622, g = 0.622, b = 0.622, a = 1.000}, -- #9f9f9fff
        }
    }
})

-- sulfur
data.raw["recipe"]["sulfur"].ingredients =
{
    {type="fluid", name="LaNMod-oil", amount=20},
    {type="fluid", name="steam", amount=60},
    {type="item", name="coal", amount=8}
}
data.raw["recipe"]["sulfur"].results=
{
    {type="item", name="sulfur", amount=8}
}
data.raw["recipe"]["sulfur"].energy_required = 4

-- lubricant
data.raw["recipe"]["lubricant"].ingredients =
{
    {type="fluid", name="LaNMod-oil", amount=10},
    {type="fluid", name="steam", amount=10},
    {type="item", name="sulfur", amount=4}
}
data.raw["recipe"]["lubricant"].order = "g[lubricant]"

-- empty-barrel
-- No changes to empty barrel (the one from steel).
